iOdra/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', include('telephones.urls', namespace="contactApp")),
    path('', include('mainMap.urls', namespace="mainMap")),
]

mainMap/urls.py
from django.urls import path
from .views import landing_view, map_view, chunk_view, messages_view, locks_table_view, lock_details, marina_details, weir_details, search, water_safety_view
from django.conf import settings
from django.conf.urls.static import static

app_name = 'mainMap'

urlpatterns = [
    path('', landing_view, name="landing"),
    path('map/', map_view, name="map"),
    path('komunikaty/', messages_view, name="komunikaty"),
    path('sluzy/', locks_table_view, name="sluzy"),
    path('bezpieczenstwo/', water_safety_view, name="water_safety"),
    path('sluza/<str:slug>', lock_details, name="sluza_details"),
    path('marina/<str:slug>', marina_details, name="marina_details"),
    path('jaz/<str:slug>', weir_details, name="jaz_details"),
    path('map/search/', search, name="search"),
    path('map/<str:slug>/', chunk_view, name="chunk"),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

telephones/urls.py
from django.urls import path, include
from .views import contact_view
from django.conf import settings
from django.conf.urls.static import static

app_name = 'contactApp'

urlpatterns = [
    path('', contact_view, name="contact"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <script src="{% static 'minified/gsap.min.js'%}" type="text/javascript"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

  </head>
  <body>
  <ul class="navbar">
    <li class="navbar-li landing-nav"><a href="{% url 'mainMap:landing' %}">STRONA GŁÓWNA</a></li>
    <li class="navbar-li map-nav"><a href="{% url 'mainMap:map' %}">MAPA</a></li>
    <li class="navbar-li komunikaty-nav"><a href="{% url 'mainMap:komunikaty' %}">KOMUNIKATY</a></li>
    <li class="navbar-li water_safety-nav"><a href="{% url 'mainMap:water_safety' %}">BEZPIECZENSTWO</a></li>
    <li class="navbar-li sluzy-nav"><a href="{% url 'mainMap:sluzy' %}">ŚLUZY</a></li>
    <li class="navbar-li telefony-nav"><a href="{% url 'contactApp:contact'%}">TELEFONY</a></li>
  </ul>

  {% block content %}
  {% endblock %}
  <div class="footer">
    <p class="description">Projekt współfinansowany
  ze środków Gminy Wrocław</p>
 
  <div style="display: flex; flex-flow: column; justify-content: center;">
    <p class="website" style="margin-bottom: 10px;">www.wrocław.pl</p>
    <img src="{% static 'website_images/wrocaw-logo-white-black.png' %}" alt="" style="width: 250px; height: 25px; margin: 0 auto;">
  </div>
  
  <div class="odra-centrum-logo">
    <img src="{% static 'website_images/onwater_logo.png'%}" alt="" style="height: 50px; width:auto; margin-right: 50px;">
  
    <img src="{% static 'website_images/logo_odra_centrum.png'%}" alt="" style="height: 60px; width:auto; margin-top: -10px;">
  
  </div>
  </div>
  <script type="text/javascript" src="{% static 'script.js' %}"></script>
  </body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'contactApp/contact.css'%}">
<h1 class="contact-title">Punkt Odrzańskiej Informacji Turystycznej</h1>

{% for block, info in data %}
<div class="info_block">
  <div class="info_img">
    <img class="infoimg" src="{% static 'website_images/arrow.png' %}" alt="">
  </div>
  <div class="info_container">
    <h3 class="info_header">{{block.title}}</h3>
    <div class="info_wrapper">
      {% for unit in info %}
      <div class="info_block_small">      
        {% if unit.title %}<p class="small_header">{{unit.title}}</p> {% endif %}
        <p class="small_text">
          {{unit.description|linebreaks}}
        </p>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endfor %}

<script src="{% static 'contactApp/contact.js' %}">

</script>

{% endblock %}

templates/komunikaty.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'mainMap/komunikaty.css'%}">
<h1 class="komunikaty-title">Punkt Odrzańskiej Informacji Turystycznej</h1>
<div class="container">
  {% for item in komunikaty %}
  {% for line in item %}
  {% if forloop.counter == 1 %}
  <div class="title-div">
    <h3 class="title">{{line}}</h3>
  </div>
  {% elif forloop.counter == 2 %}
  <div class="date-div">
    <p class="date">{{line}}</p>
  </div>

  {% else %}
  <p class="text">{{line}}</p>
  {% endif %}

  {% endfor %}
  <div class="divider"></div>
  {% endfor %}
</div>


{% endblock %}

templates/landing.html
{% load static %}
<link rel="stylesheet" href="{% static 'mainMap/landing.css' %}">
<div class="outter">
<div class="slider">
  <div class="slide slide1"></div>
  <div class="slide slide2"></div>
  <div class="slide slide3"></div>
  <div class="slide slide4"></div>
  <div class="slide slide1"></div>
</div>
</div>


<a class="to non-blur" href="{% url 'mainMap:map'%}">
<div class="hello-container blur">
<p class="non-blur">Punkt Odrzańskiej Informacji Turystycznej</p>
<img class="app_logo non-blur" src="{% static 'website_images/logo_iodra.png'%}" alt="">
  <div class="more non-blur">
    <img src="{% static 'website_images/arrow.png'%}" alt="" class="rotate non-blur">
    <p class="non-blur">ROZPOCZNIJ</p>
    <img src="{% static 'website_images/arrow.png'%}" alt="" class="non-blur">
  </div>
</div>
</a>
<a href="https://odracentrum.org/">
  <div class="website-href-container">
    <img src="{% static 'website_images/logo_oc_transparent.png' %}" alt="">
    <p>ZOBACZ NAJNOWSZE WYDARZENIA<br><span>W ODRA CENTRUM</span> </p>
  </div>
</a>



<div class="footer">
  <p class="description">Projekt współfinansowany
ze środków Gminy Wrocław</p>

<div style="display: flex; flex-flow: column; justify-content: center;">
  <p class="website" style="margin-bottom: 10px;">www.wrocław.pl</p>
  <img src="{% static 'website_images/wrocaw-logo-white-black.png' %}" alt="" style="width: 250px; height: 25px; margin: 0 auto;">
</div>

<div class="odra-centrum-logo">
  <img src="{% static 'website_images/onwater_logo.png'%}" alt="" style="height: 50px; width:auto; margin-right: 50px;">

  <img src="{% static 'website_images/logo_odra_centrum.png'%}" alt="" style="height: 60px; width:auto; margin-top: -10px;">

</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/barba.js/0.0.2/barba.min.js" charset="utf-8"></script>

templates/locks.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'mainMap/locks.css' %}">

<h1 class="header">Punkt Odrzańskiej Informacji Turystycznej</h1>

<div class="table-div">
  <table>
    <tr>
      <th class="top left bottom right">Nazwa stopnia wodnego</th>
      <th class="top bottom right ">Kilometr Odry</th>
      <th class="top bottom right">Numer telefonu</th>
      <th class="top right bottom right">Status śluzy</th>
    </tr>
    {% for lock in locks %}
    <tr>
      <td class="name left bottom right">{{lock.nazwa_stopnia_wodnego}}</td>
      <td class="kilometer bottom right">{{lock.km_odry}}</td>
      <td class="phone bottom right">{{lock.nr_tel}}</td>
      <td class="state right bottom">{{lock.status_sluzy}}</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

templates/mapChunk.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'mainMap/mapChunk.css' %}">
<div class="head">
  <a href="{% url 'mainMap:map' %}" class="return-a">
    <div class="return">
      <img src="{% static 'website_images/back_arrow.png'%}" alt="">
      <p>Powrót do mapy</p>
    </div>
  </a>

  <form class="form-inline nav-form buttonInside" method="POST" action="{% url 'mainMap:search' %}">
    {% csrf_token %}
    <input type="hidden" name="slug" value="{{chunk.slug}}">
    <input class="nav-input" placeholder="Wyszukaj miejsce" name="input">
    <button class="nav-button" type="submit">
      <img src="{% static 'website_images/search_icon.png'%}" alt="">
    </button>
  </form>
</div>
<h3 class="mapChunkTitle">Punkt Odrzańskiej Informacji Turystycznej</h3>
<div class="parent" style="background-image: url('{{chunk.image.url}}'); background-position: center; background-repeat: no-repeat;">

</div>

<!-- strzałki do przechodzenia pomiędzy chunkami -->

{% if next %}
<a href="{{next.get_absolute_url}}">
  <div class="arrow-left">
    <img src="{% static 'website_images/right_arrow.png'%}" alt="">
    <p>{{next.part}}</p>
  </div>
</a>
{% endif %}
{% if prev %}
<a href="{{prev.get_absolute_url}}">
  <div class="arrow-right">
      <img src="{% static 'website_images/left_arrow.png'%}" alt="">
      <p>{{prev.part}}</p>
  </div>
</a>
{% endif %}


<!-- renderowanie śluz iterując po query -->

{% for lock in locks %}
<div class="sluza" data="{{lock.slug}}" style="position: absolute; left: {{lock.x_pos}}px; top: {{lock.y_pos}}px; background-color: {% if lock.state %}#4A8500{% else %}#852000{% endif %}">
Ś
</div>
{% endfor %}

<!-- renderowanie marin iterując po query -->

{% for marina in marinas %}
<div class="marina" data="{{marina.slug}}" style="position: absolute; left: {{marina.x_pos}}px; top: {{marina.y_pos}}px; background-color: {% if marina.state %}#011C40{% else %}#852000{% endif %}">
M
</div>
{% endfor %}

<!-- renderowanie jazow iterując po query -->

{% for weir in weirs %}
<div class="jaz" data="{{weir.slug}}" style="position: absolute; left: {{weir.x_pos}}px; top: {{weir.y_pos}}px; background-color: {% if weir.state %}#4A8500{% else %}#852000{% endif %}">
J
</div>
{% endfor %}


<div class="info blur">

</div>
<!-- ORYGINAŁ, DO EWENTUALNEJ ZMIANY DESIGNU ODKOMENTOWAĆ-->

<!-- <div class="info blur">
  <div class="info-sub non-blur">
    <div class="left non-blur">
      <div class="inline-chunk">
        <span id="marina-filter" class="marina-checkbox checkbox"><p>M</p></span>
        <p class="object_title">ŚLUZA MIESZCZAŃSKA</p>
      </div>
      <div class="object_image" style="width: 80%; height: 100%; margin: 20px auto; background-position: center center; background-image: url('{% static 'website_images/pobrane.jpg'%}'); background-repeat: no-repeat; background-size: cover;">

      </div>
    </div>
    <div class="right non-blur">
      <p class="object_info1">
        252,3 km Odry południowej
        Wrocławski Szlak Śródmiejski </p>
      <p class="object_info2">
        długość – 42,8m
        szerokość – 5,3m
        piętrzenie - 5,65m
      </p>
      <p class="object_info3">Nr tel.: 502-331-251
  Otwarta pon.: 06:30 - 14:00
  pozostałe dni tygodnia i święta 06:30-21:30</p>
    </div>
  </div>
  <p class="info4 non-blur">
    Odległość do następnego stopnia – Śluz Rędzin, wynosi 8,3 km,
    do poprzedniej na szlaku Śluzy Piaskowej wynosi 0,6 km
  </p>
</div> -->

<div class="filters">
  <p class="filters-header">Filtruj:</p>
  <div class="filters-content">
    <div class="filter-unit">
      <span id="lock-filter" class="lock-checkbox checkbox"><p>Ś</p></span>
      <p class="label">Śluzy</p>
    </div>
    <div class="filter-unit">
      <span id="marina-filter" class="marina-checkbox checkbox"><p>M</p></span>
      <p class="label">Mariny</p>
    </div>
    <div class="filter-unit">
      <span id="weir-filter" class="weir-checkbox checkbox"><p>J</p></span>
      <p class="label">Jazy</p>
    </div>
  </div>
</div>
<div class="scale-div">
  <p>Wybrany odcinek:</p>
  <p>{{chunk.part}}</p>
</div>

<script type="text/javascript" src="{% static 'mainMap/mapChunk.js'%}">

</script>

{% endblock %}

templates/water_safety.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="{% static 'style.css' %}">
<link rel="stylesheet" href="{% static 'mainMap/water_safety.css' %}">
<div class="">
  <h1 class="header">Punkt Odrzańskiej Informacji Turystycznej</h1>
  <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="30000">
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="{% static 'website_images/bezpieczeństwo/1.png' %}" alt="Los Angeles" style="width:100%;">
      </div>

      <div class="item">
        <img src="{% static 'website_images/bezpieczeństwo/2.png' %}" alt="Chicago" style="width:100%;">
      </div>

      <div class="item">
        <img src="{% static 'website_images/bezpieczeństwo/3.png' %}" alt="New york" style="width:100%;">
      </div>

      <div class="item">
        <img src="{% static 'website_images/bezpieczeństwo/4.png' %}" alt="New york" style="width:100%;">
      </div>

      <div class="item">
        <img src="{% static 'website_images/bezpieczeństwo/5.png' %}" alt="New york" style="width:100%;">
      </div>

    </div>

    <!-- Left and right controls -->
  </div>
  <a class="left carousel-control no-backgroud" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control no-backgroud" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
{% endblock %}
<script type="text/javascript" src="{% static 'script.js' %}">

</script>
</body>
</html>